version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: escuela_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123.Hola
      MYSQL_DATABASE: escuela_db
      MYSQL_USER: escuela_user
      MYSQL_PASSWORD: 123.Hola
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-123.Hola",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - escuela_network

volumes:
  mysql_data:
    driver: local

networks:
  escuela_network:
    driver: bridge
